# Generated by Django 2.2.6 on 2019-10-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='imprient',
            new_name='imprint',
        ),
    ]
